JupiterOne/jupiterone-alert-rules

rule-packs/index.js

Adding this index file makes it possible to easily use the rule packs in code. Tested and verified that it works locally.

Add index file

---

package.json
rule-packs/compliance.json
rule-packs/index.js

Adds a rule pack that users can import to get alerts on open compliance gaps.
Keeping it simple for now, we can add additional alerts later.

CORE-2381 - add compliance rule pack

---

rule-packs/aws-config.json

Temporarily reverting back aws-config file until we can identify error that happened.

reverting back to previous state.

---

rule-packs/azure.json

add azure vm disablePasswordAuth

---

rule-packs/aws-config.json

Removed duplicate rules and updated description

---

package.json

The below is N/A - I am just bumping the package here to publish the recent changes (specifically [this](https://github.com/JupiterOne/jupiterone-alert-rules/pull/70) one). If there's a new process for this that I'm unaware of, please let me know!

APP-11212 - Publish new package version

---

package.json
rule-packs/device-management.json
rule-packs/index.js
rule-packs/toxic-combinations.json

No ticket add rule packs

---

rule-packs/aws-threat.json

adding directionals to ssh-keys-shared rule

---

rule-packs/intergration-monitoring.json

updated rule description and query

---

README.md
package.json
rule-packs/index.js
rule-packs/integration-monitoring.json

[APP-14290] - Fix and export integration monitoring rule pack

---

rule-packs/aws-config.json

https://aws.amazon.com/blogs/security/get-the-full-benefits-of-imdsv2-and-disable-imdsv1-across-your-aws-infrastructure/
```
"MetadataOptions": {
"State": "applied", 
"HttpEndpoint": "enabled", 
"HttpTokens": "optional", 
"HttpPutResponseHopLimit": 1
},
```

KNO-371 - Update aws-config.json

---

rule-packs/aws-config.json

Fix up queries that were incorrectly negating traversals, and aliasing the results

Fix up queries that were incorrectly negating traversals

---

package.json
rule-packs/cyberark-idaptive-misconfigurations.json
rule-packs/index.js

Mikiodehartj1 patch 3

---

rule-packs/azure.json

removing question

---

scripts/validate.ts

APP-15732 - Add validation for labels field

---

package.json
rule-packs/index.js
rule-packs/mitre-attck-lateral-movement-attack-paths.json
yarn.lock

new rule pack lateral movement

---

package.json
rule-packs/index.js
rule-packs/jupiterone-sbom.json

adding new rule pack

---

package.json
rule-packs/index.js
rule-packs/kubernetes-cis.json

Add cis 5.1.1-5.1.13 as rule pack rules

---

package.json
rule-packs/kubernetes-cis.json

Kube cis 5.2

---

package.json
rule-packs/kubernetes-cis.json

Kube CIS 5.3.2-5.6.4
